"""Initial migration - create source_db, registry, and mapping tables
Revision ID: 9f53da407469
Revises: c140982ec9d2
Create Date: 2025-09-04 11:13:39.191467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f53da407469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_entity_id'), 'entity', ['id'], unique=False)
    op.create_table('source_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name')
    )
    op.create_index(op.f('ix_source_db_id'), 'source_db', ['id'], unique=False)
    op.create_table('registry',
    sa.Column('source_db_id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_db.id'], ),
    sa.PrimaryKeyConstraint('source_db_id', 'entity_type_id', 'local_id'),
    )
    op.create_table('mapping',
    sa.Column('source_db_id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.String(length=255), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['source_db_id', 'entity_type_id', 'local_id'], ['registry.source_db_id', 'registry.entity_type_id', 'registry.local_id'], name='fk_mapping_registry', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_db_id'], ['source_db.id'], ),
    sa.PrimaryKeyConstraint('source_db_id', 'entity_type_id', 'local_id'),
    )

    # Seed Entity (1: gene, 2: strain)
    op.execute("""
        INSERT INTO entity (id, name) VALUES
            (1, 'gene'),
            (2, 'strain')
        ON CONFLICT (id) DO UPDATE
            SET name = EXCLUDED.name;
    """)

    # Seed source_db with fixed ids and canonical names
    # 1 Bigg, 2 ALEdb, 3 PMKbase, 4 Pankb
    op.execute("""
        INSERT INTO source_db (id, db_name) VALUES
            (1, 'Bigg'),
            (2, 'ALEdb'),
            (3, 'PMKbase'),
            (4, 'Pankb')
        ON CONFLICT (id) DO UPDATE
            SET db_name = EXCLUDED.db_name;
    """)


def downgrade() -> None:
    op.execute("DELETE FROM source_db WHERE id IN (1,2,3,4);")
    op.execute("DELETE FROM entity WHERE id IN (1,2);")
    op.drop_table('mapping')
    op.drop_table('registry')
    op.drop_index(op.f('ix_source_db_id'), table_name='source_db')
    op.drop_table('source_db')
    op.drop_index(op.f('ix_entity_id'), table_name='entity')
    op.drop_table('entity')
    
    # ### end Alembic commands ###